alvarocaid/krowd-page

- style/styles.css
- user-home.html
> feat: user-home.html

- index.html
- style/login_popup.css
Se agrego un pop up de login, que tiene la siguientes caracteristicas:
- 2 cajas de inputs, donde el usuario podrá colocar tanto su usuario como su contraseña 
- Un boton de login con el que podra logearse
> feat: login-pop up agregado

- index.html
- style/login_popup.css
validacion de login con pop up que dice "correo invalido o contraseña"
> feat: login-validation agreagado

- index.html
- style/login_popup.css
se agrego un pop up de sign up para poder registrarse, el mismo maquetado que el de del log in
> feat: signup-popup-user

- Referred-Link.html
- style/Referred-Link.css
Se agrego la página en configuración para poder copiar el link y enviarlo a los amigos 
del  usuario donde también saldrá que usuarios se han registrado con dicho enlace
se modifico el html de Configuration_home para poder redireccionar en el apartado de compartir enlace referido
> feat: Se agrego la pagina para poder un link referido a tus amigos

- index.html
- Cuando el usuario inicia sesión correctamente con usuario admin y contraseña 1234 en  `index.html`, es redirigido automáticamente a `user-home.html`
- Si las credenciales son incorrectas, se muestra un popup de error.
> feat: navegacion de index a userhome

- style/user-Panel-Creador-Rewards-Ads.css
- user-Panel-Creador-Rewards-Ads.html
Se añadio la opcion de rewards ads en el apartado de panel de control del creador
Se añadio un boton que tiene dos estados:
1- boton en off nos informara cuando la opcion de rewards ads no este activa mostrandonos un mensaje de "No recibiras ingresos"
2-boton en on nos informara cuando la opcion de rewards ads este activada mostrandonos un mensaje de "Recibiras ingresos en el apartado de analisis"
> feat:Es el panel donde el creador activa sus Rewards Ads

- creadores-sugeridos.html
- style/styles.css
- user-home.html
Se implementó la navegación lateral en los archivos HTML de las secciones de usuario y creadores sugeridos para mejorar la experiencia del usuario.
Detalles
- El menú lateral permite la navegación entre "Home" y "Creadores Sugeridos" mediante enlaces.
- Cuando el usuario se encuentra en el archivo HTML de la sección Home, el ítem correspondiente aparece resaltado como activo.
> feat: navegacion de user-home a creadores-sugeridos y viceversa

- Configuracion-home.html
- Problem_Report.html
- Referred-Link.html
- creadores-sugeridos.html
- user-home.html
Implementación de navegación lateral entre las secciones Home, Creadores Sugeridos y Configuración. El menú lateral permite moverse fácilmente entre estas páginas, mostrando visualmente el estado activo del ítem correspondiente para mejorar la orientación y experiencia de usuario dentro de la plataforma.
> feat: navegación lateral entre Home y Configuracion

- index.html
- style/login_popup.css
Se implementó un sistema de popups personalizados para el registro de usuarios. Ahora, cuando un usuario se registra correctamente, aparece un popup de bienvenida con su nombre. Si el usuario intenta registrarse con campos vacíos o datos no válidos, se muestra un popup de error con un mensaje claro.
> feat:validation-signup

- index.html
Cuando el usuario se registra correctamente, aparece un popup de bienvenida y, al cerrarlo, es redirigido automáticamente a la página principal de usuario.
> feat:register-to-user-home

- configuracion-canal-creador.html
- configurar-transmision.html
- item-configuracion.html
Implemente el panel de configuración del creador, permitiendo personalizar el canal, gestionar campos obligatorios y opcionales, y validar la subida de portada (solo archivos .png o .jpg). Incluye feedback visual mediante mini modales para éxito o error, navegación entre secciones del panel y controles interactivos para categorías, micrófono y cámara. Todo el flujo mantiene la coherencia visual y de experiencia del panel de control del creador.
> feat:Configuracion del panel de creadores de contenido: configuracion

- style/styles.css
Se cambio el boton de login-signpu por un mejorado de fondo de color diferente, de acuerdo a nuestra paleta de colores
> feat: boton de login mejorado

- index.html
Se agrego un signup para el creador, donde también estas las validaciones
> feat:signup de creador agregado

- Configuracion-home.html
- Problem_Report.html
- Referred-Link.html
- canal-display.html
- creadores-sugeridos.html
- style/styles.css
- user-home.html
> feat: se agrego un boton de logout

- index.html
navegar hacia el home de creador cuando el creador se registro
> feat: navegar hacia el home de creador

- user-Panel-Creadores.html
Se implemento la funcion editar en los cuadrados del panel de Creador de contenido para cambiar o aumentar la informacion
> Implemente la funcion editar de los cuadrados del Panel de Creadores de contenido

- Gestor-del-Stream.html
Implemente la fución de "Sugerencias para Crecer"  en el Gestor del Stream
> Actualicé Gestor del Stream con funcinalidad en Sugerencias para crecer

- Analisis.html
se agrego un cuadro de ganancias por Anuncios
> Actualicé la Seccion analisis con el cuadro de anuncios

- style/Problem_Report.css
- style/Referred-Link.css
Se hizo un pequeño cambio de color en la flecha que se usa para retroceder a configurar desde reportar un problema o copiar link de referido
> fix: Se cambio el color de la flecha segun el feedback mostrado

- canal-display.html
Se agregó un aviso de que se gano los créditos correspondientes luego de ver todo el anuncio.
> feat:agregar-aviso-de-creditos

- canal-display.html
Se agregó lógica para seguir a un creador mediante el botón "Seguir". Aparecera un mensaje que te indicara que lo comenzaste a seguir.
> feat:se agrego logica del boton de seguir al creador

- Configuracion-home.html
- Configuracion-home.js
- Problem_Report.html
- Problem_Report.js
- style/Problem_Report.css
Se implementaron archivos js para dar un mayor orden 
se implemento un apartado para poder visualizar el estado del reporte
dicho reportes tendrán los siguientes estados:
pendiente
rechazado 
realizado
solo se observaran los últimos 3 reportes mandados
> 'feat: se implemento logica para el reporte

- Analisis.html
Se reorganizó el panel de Análisis y se eliminó la carga visual.
> Actualizo Analisis.html

- user-Panel-Creadores.html
Se cambio el cuadro al presionar el boton de Editar, tambien se agrego el la funcion para pasar de "Panel del Creador" a "Gestor del Stream"
> Actualizo user-Panel-Creadores.html

- Configuracion-Canal-creador.js
- Configurar_Transmision.js
- MetodoPago_UserPanelCreador.js
- Rewards-Ads-UserPanelCreador.js
- configuracion-canal-creador.html
- configurar-transmision.html
- item-configuracion.html
- user-Panel-Creador-Rewards-Ads.html
Se borro las partes donde se usa javascript en los archivos .html para mejorar el orden y se agrego los siguientes archivos .js para que no se pierda la interaccion: 
Configuracion-Canal-creador.js
Configurar_Transmision.js
MetodoPago_UserPanelCreador.js
Rewards-Ads-UserPanelCreador.js
> feat: se implemento carpetas js (javascript) para el orden

- Analisis.html
- CentroSeguridad.html
- Gestor-del-Stream.html
- configuracion-canal-creador.html
- configurar-transmision.html
- item-configuracion.html
- user-Panel-Creador-Rewards-Ads.html
- user-Panel-Creadores.html
Se ha añadido un botón de 'log out' para que los creadores puedan salir de sus cuentas fácilmente.
> Se agrego el boton de log out

- Configuracion-home.html
Se quito la barra de trends en el archivo de 'Configuracion-home.html'
> fix: quitar barra de trends

- style/Configuracion-home.css
- style/Problem_Report.css
se arreglo la flecha de mandar un reporte
> fix: se arreglo la flecha correctamente
